### ISSUE TITLE
Package cleanup

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/tidy-animated-verbs#15]
- [x] Replace few stringr calls with base R
- [x] Qualify package namespaces for non-imported functions
- [ ] ~~De-pipe single command pipes~~
- [x] Remove final-line `return()` statements in functions

**Comment by DavZim** [comment]
Fixed stringr issues with bfa7255a92b1f76a4b6fddda1feececbf8999f07
Also, reduced the number of single command pipes,
Why do you want to remove return()-calls (just curious) :)

**Comment by gadenbuie** [comment]
Mostly because http://style.tidyverse.org/functions.html#return

But also modifying or storing an object right before return, like here https://github.com/gadenbuie/tidy-animated-verbs/blob/256448d876ac08111420133a31fa62c313094b41/R/move_together.R#L96-L105

reads to me like an indicator that the object `res` was created earlier in the function. Whereas just creating and returning in the same line indicates that the pieces are made earlier in the function and you're just assembling them before returning.

So having this function end with

```r
bind_rows(
  # take,
  take_vals,
  # fade in place:
  all %>% filter(!.id_long %in% take_ids$.id_long) %>% mutate(.alpha = 0),
  # moving fade or fade in place as well:
  all %>% filter(.id_long %in% take_ids$.id_long & !.col %in% take_cols$.col) %>%
    mutate(.alpha = 0)
)
```

communicates that I only need to understand how `take_vals` and `all` are created to understand what comes out of the function.

Ultimately it's subjective and comes down to style (both do the same thing!), so I hope this came across as constructive and not as a critique. :)

**Comment by DavZim** [comment]
Ah, I was always unsure what to do (stylewise). Makes sense, thanks for the clarification.
That was definitely constructive and not negative critique :) Will try to change the returns tonight

**Comment by gadenbuie** [comment]
I changed my mind about single-pipe lines, they're not my usual style but I've found I don't mind them when reading your code. :)

I cleaned up the return statements, but I also found this example of a really good reason to have a `return(res)` call at the end of `add_color_join()`:

https://github.com/gadenbuie/tidy-animated-verbs/blob/256448d876ac08111420133a31fa62c313094b41/R/process_data_helpers.R#L143-L146
