### ISSUE TITLE
tidyr :: pivot_wider() and pivot_longer()

### ISSUE THREAD

**Issue by bjungbogati** [gadenbuie/tidy-animated-verbs#27]
Animation request for pivot_wider() and pivot_longer().

Background: “Pivotting” which converts between long and wide forms. tidyr 1.0.0 introduces pivot_longer() and pivot_wider(), replacing the older spread() and gather() functions. See vignette("pivot") for more details.

Link: https://tidyr.tidyverse.org/

**Comment by kelseygonzalez** [comment]
I came to request the same update 😄 . I'm a maintainer of the [data carpentry R for Social Science](https://datacarpentry.org/r-socialsci/) lesson and we've been hunting for a better visualization to use when teaching pivotting. We'd love to be able to use yours and give you credit!
