### ISSUE TITLE
Publish animations on companion github pages...

### ISSUE THREAD

**Issue by dan-reznik** [gadenbuie/tidy-animated-verbs#29]
... so the animation becomes visible (README.md doesn't support animations I think)

**Comment by gadenbuie** [comment]
That's odd, the animations work for me when viewed through the README on GitHub. In terms of having a more friendly page for everything, I published a copy of the README on my webpage at https://garrickadenbuie.com/project/tidyexplain ... thanks to your comment I realized I hadn't yet linked to it from the GitHub repo, so I just changed that now.
